- name: installing package
  hosts: all
  tasks:
  - name: installing apache2 on clientmachine
    apt:
      name: apache2
      state: present
  - name: Create new User
    user:
      name: bokaa
      state: present
